[workspace]
members = ["benchmarks", "integration-tests", "remote-table", "remote-table/gen"]
resolver = "3"

[workspace.dependencies]
datafusion = "55"
datafusion-proto = "55"
arrow = { version = "59", features = ["chrono-tz"] }
datafusion-common = "55"
datafusion-execution = "55"
datafusion-expr = "55"
datafusion-physical-plan = "55"
datafusion-physical-expr = "55"
datafusion-catalog = "55"
datafusion-datasource = "55"
datafusion-sql = "55"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.40" }
prost = "0.14"
prost-build = "0.14"
odbc-api = { version = "28.1.1", default-features = false, features = ["odbc_version_3_80"]}