name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build with all features
        run: cargo check -p datafusion-remote-table --all-features

      - name: Build with only postgres
        run: cargo check -p datafusion-remote-table --no-default-features --features postgres

      - name: Build with only mysql
        run: cargo check -p datafusion-remote-table --no-default-features --features mysql

      - name: Build with only oracle
        run: cargo check -p datafusion-remote-table --no-default-features --features oracle

      - name: Build with only sqlite
        run: cargo check -p datafusion-remote-table --no-default-features --features sqlite

      - name: Build with only dm
        run: cargo check -p datafusion-remote-table --no-default-features --features dm

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install oracle instant client
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
          mkdir -p /opt/oracle
          cd /opt/oracle
          wget https://download.oracle.com/otn_software/linux/instantclient/2370000/instantclient-basic-linux.x64-23.7.0.25.01.zip
          unzip instantclient-basic-linux.x64-23.7.0.25.01.zip
          echo "LD_LIBRARY_PATH=/opt/oracle/instantclient_23_7" >> $GITHUB_ENV

      - name: Install ODBC driver manager
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev

      - name: Run unit tests
        run: cargo test -p datafusion-remote-table

      - name: Run integration tests
        # There is no easy way to install dm odbc driver, so skip dm integration tests
        run: cargo test -p integration-tests --test common --test sqlite --test postgres --test mysql --test oracle

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install rustfmt and clippy
        run: rustup component add rustfmt clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all -- -D warnings